package com.com.raymond.downloader.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.raymond.mvpdemo.model.bean.UserInfo;
import com.example.raymond.mvpdemo.model.bean.Label;
import com.example.raymond.mvpdemo.model.bean.UserIcon;

import com.com.raymond.downloader.greendao.UserInfoDao;
import com.com.raymond.downloader.greendao.LabelDao;
import com.com.raymond.downloader.greendao.UserIconDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig labelDaoConfig;
    private final DaoConfig userIconDaoConfig;

    private final UserInfoDao userInfoDao;
    private final LabelDao labelDao;
    private final UserIconDao userIconDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        labelDaoConfig = daoConfigMap.get(LabelDao.class).clone();
        labelDaoConfig.initIdentityScope(type);

        userIconDaoConfig = daoConfigMap.get(UserIconDao.class).clone();
        userIconDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        labelDao = new LabelDao(labelDaoConfig, this);
        userIconDao = new UserIconDao(userIconDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(Label.class, labelDao);
        registerDao(UserIcon.class, userIconDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        labelDaoConfig.clearIdentityScope();
        userIconDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public LabelDao getLabelDao() {
        return labelDao;
    }

    public UserIconDao getUserIconDao() {
        return userIconDao;
    }

}
