package com.com.raymond.downloader.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.raymond.mvpdemo.model.bean.TalkContext;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TALK_CONTEXT".
*/
public class TalkContextDao extends AbstractDao<TalkContext, Long> {

    public static final String TABLENAME = "TALK_CONTEXT";

    /**
     * Properties of entity TalkContext.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uid = new Property(1, Long.class, "uid", false, "UID");
        public final static Property Questionid = new Property(2, Long.class, "questionid", false, "QUESTIONID");
        public final static Property TalkContext = new Property(3, String.class, "talkContext", false, "TALK_CONTEXT");
    }


    public TalkContextDao(DaoConfig config) {
        super(config);
    }
    
    public TalkContextDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TALK_CONTEXT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"UID\" INTEGER," + // 1: uid
                "\"QUESTIONID\" INTEGER," + // 2: questionid
                "\"TALK_CONTEXT\" TEXT);"); // 3: talkContext
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TALK_CONTEXT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TalkContext entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(2, uid);
        }
 
        Long questionid = entity.getQuestionid();
        if (questionid != null) {
            stmt.bindLong(3, questionid);
        }
 
        String talkContext = entity.getTalkContext();
        if (talkContext != null) {
            stmt.bindString(4, talkContext);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TalkContext entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(2, uid);
        }
 
        Long questionid = entity.getQuestionid();
        if (questionid != null) {
            stmt.bindLong(3, questionid);
        }
 
        String talkContext = entity.getTalkContext();
        if (talkContext != null) {
            stmt.bindString(4, talkContext);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TalkContext readEntity(Cursor cursor, int offset) {
        TalkContext entity = new TalkContext( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // questionid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // talkContext
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TalkContext entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setQuestionid(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTalkContext(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TalkContext entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TalkContext entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TalkContext entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
